version: '3.9'

services:
  frontend:
    container_name: angularfrontend
    build:
      context: .
      dockerfile: Dockerfile
  nginx:
    container_name: middlenginx
    image: nginx:latest
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
